# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
