# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20170219_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
