# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20170219_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pnotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnotes', models.TextField()),
            ],
        ),
    ]
